# These are supported funding model platforms

github: [AyhamAsfoor]
patreon: [patreon.com/AyhamAsfoor]
open_collective: [] 
ko_fi: []
tidelift: []
community_bridge: []
liberapay: []
issuehunt: []
otechie: []
custom: ['https://www.linkedin.com/in/ayham-asfoor-949630256/']
